# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - restbeks(restbeks)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e354615de8c0456b837e7f2e203fcc73 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e3aeb88958a349189dc6e2d3a58124e3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e354615de8c0456b837e7f2e203fcc73 }}/restbeks:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'restbeks'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restbeks'
        slot-name: 'restbeks'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2d3a7a77baea4731aca30fd7c9882edd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e354615de8c0456b837e7f2e203fcc73 }}/restbeks:${{ github.sha }}'